# Generated by Django 6.0.6 on 2026-07-18 17:01

import core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='delivery_notes',
            field=models.TextField(blank=True, help_text='Optional extra info for the buyer: recovery email, 2FA backup codes, transfer instructions, etc.'),
        ),
        migrations.AddField(
            model_name='product',
            name='login_identifier',
            field=models.CharField(blank=True, help_text='The username, email, or handle used to log in to the account.', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='login_password',
            field=core.fields.EncryptedTextField(blank=True, help_text='Encrypted at rest. Only ever shown to the buyer after purchase.'),
        ),
    ]
