# Generated by Django 6.0.6 on 2026-07-18 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_delivery_notes_product_login_identifier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('sold', 'Sold')], db_index=True, default='available', max_length=20),
        ),
    ]
