# Generated by Django 6.0.6 on 2026-07-31 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_category_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='profile_url',
            field=models.URLField(blank=True, help_text="Link to the account/profile for buyers to preview (e.g. Instagram profile URL). Leave blank to hide the 'Visit Profile' button on the listing.", null=True, verbose_name='Profile link'),
        ),
    ]
